services:
  oracle-db:
    image: gvenzl/oracle-free:23-slim
    container_name: order-source-oracle-db
    environment:
      ORACLE_PASSWORD: oracle123
      APP_USER: order_source
      APP_USER_PASSWORD: ordersource123
    ports:
      - "1522:1521"
    volumes:
      - order-source-oracle-data:/opt/oracle/oradata
    healthcheck:
      test: ["CMD", "healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    networks:
      - order-source-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: order-source-backend
    environment:
      PORT: 3579
      NODE_ENV: production
      DB_USER: order_source
      DB_PASSWORD: ordersource123
      DB_CONNECTION_STRING: oracle-db:1521/FREEPDB1
      DB_POOL_MIN: 2
      DB_POOL_MAX: 10
      DB_POOL_INCREMENT: 2
      SYSTEM_USER: system
      SYSTEM_PASSWORD: oracle123
    ports:
      - "3579:3579"
    depends_on:
      oracle-db:
        condition: service_healthy
    networks:
      - order-source-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: order-source-frontend
    environment:
      REACT_APP_API_URL: http://localhost:3579/api
    ports:
      - "3578:80"
    depends_on:
      - backend
    networks:
      - order-source-network
    restart: unless-stopped

volumes:
  order-source-oracle-data:

networks:
  order-source-network:
    driver: bridge
